"use client";

import { useState, useEffect } from "react";
import type { MouseEventHandler } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { LazyImage } from "./components/LazyImage";
import { random } from "lodash";

const generateId = (): string => {
  return (
    Math.random().toString(36).substring(2, 15) +
    Math.random().toString(36).substring(2, 15)
  );
};

const myRandom = () => random(1, 123);

const Home: NextPage = () => {
  const [images, setImages] = useState<Array<IFoxImageItem>>([]);
  const [isScrollable, setIsScrollable] = useState(false);

  useEffect(() => {
    const checkScrollability = () => {
      const { scrollHeight, clientHeight } = document.documentElement;
      setIsScrollable(scrollHeight > clientHeight);
    };

    checkScrollability();
    window.addEventListener("resize", checkScrollability);
    return () => window.removeEventListener("resize", checkScrollability);
  }, []);

  useEffect(() => {
    const { scrollHeight, clientHeight } = document.documentElement;
    setIsScrollable(scrollHeight > clientHeight);
  }, [images]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = () => {
    const id = generateId();
    const url = `https://randomfox.ca/images/${myRandom()}.jpg`;
    setImages([...images, { id, url }]);
  };

  return (
    <div>
      <Head>
        <title>Lazy Foxes!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header Fijo */}
      <header className="fixed top-0 left-0 right-0 bg-amber-800 shadow-2xl z-10">
        <div className="p-1 px-4 flex items-center justify-between">
          <h1 className="text-5xl">🦊</h1>
          <h1 className="font-serif underline text-white text-4xl py-2">Foxes</h1>
          <h1 className="text-5xl">🦊</h1>
          </div>
          <div className="flex flex-col items-center">
          <button
            onClick={addNewFox}
            className="bg-amber-500 hover:bg-amber-600 text-white font-bold py-2 px-4 rounded-full mb-2"
          >
            Add new fox
          </button>
          </div>
          {isScrollable && (
          <h1 className="absolute flex bottom-0 right-0 text-white pr-2">No olvides scrollear ⬇️</h1>
        )}
      </header>

      <main className="bg-amber-500 min-h-screen pt-[120px]">
        <h1 className="text-xs text-white m-2">Hecho con amor por @tomcesped 🖤</h1>
        <h1 className="text-xs text-white m-2">API administrada por randomfox.ca</h1>
        {/* Contenedor de imágenes */}
        <div className="mt-[-60px]">
          {images.map(({ id, url }, index) => (
            <div className="p-4" key={id}>
              <LazyImage
                src={url}
                width="320"
                height="auto"
                className="mx-auto my- auto rounded-md bg-gray-300 shadow-black shadow-lg"
                onLazyLoad={(img) => {
                  console.log(`Image #${index + 1} cargada. Nodo:`, img);
                }}
              />
            </div>
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;